export const formSchema = [
  {
    interface: "input",
    type: "alphanumeric",
    label: "Customer Id",
    name: "CustId",
    placeholder: "Enter your Customer Id",
    required: true,
  },
  { 
    interface: "input",
    type: "text",
    label: "Customer Name",
    name: "CustName",
    placeholder: "Enter your Customer Name",
    required: true,
  },
  {
    interface: "numeric",
    type: "number",
    label: "Tenure",
    name: "tenure",
    placeholder: "Enter your tenure",
    required: true,
    prefix: "months",
    maxLength: 3,
  },
  {
    interface: "input",
    type: "phone",
    label: "Mobile Num",
    name: "mobNo",
    placeholder: "Enter your Mobile Number",
    required: true,
    icon: "Phone",
    postfix: "+91",
    maxLength: 10,
  },
  {
    interface: "password",
    type: "password",
    label: "Password",
    name: "password",
    placeholder: "Enter your Password",
    required: true,
  },
  {
    interface: "masked-input",
    type: "aadhar",
    label: "Aadhar No",
    name: "aadhar",
    placeholder: "Enter your aadhar",
    required: true,
    mask: 9,
    maxLength: 12,
    space: 4,
    maskedValue: "X",
  },
  {
    interface: "input-otp",
    type: "numeric",
    label: "OTP",
    name: "otp",
    placeholder: "Enter your OTP",
    required: true,
    digit: 6,
    separatorGap: 3,
  },
  {
    interface: "input",
    type: "email",
    label: "email",
    name: "Email",
    placeholder: "Enter your Email",
    required: true,
  },
  {
    interface: "numeric",
    type: "number",
    label: "pincode",
    name: "PinCode",
    placeholder: "Enter your PinCode",
    required: true,
    maxLength: 6,
  },
  {
    interface: "pan-input",
    type: "alphanumeric",
    label: "Pan Number",
    name: "pan",
    placeholder: "Enter your Pan Number",
    required: true,
  },
  {
    interface: "select",
    type: "text",
    label: "Gender",
    name: "gender",
    placeholder: "Enter your gender",
    required: true,
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
    ],
  },
  {
    interface: "multi-select",
    label: "Additional Services",
    name: "additionalServices",
    placeholder: "Select amenities...",
    required: true,
    options: [
      { label: "Extra Legroom", value: "legroom" },
      { label: "In-flight Wi-Fi", value: "wifi" },
      { label: "Lounge Access", value: "lounge" },
      { label: "Priority Boarding", value: "priority" },
    ],
  },
  {
    interface: "date",
    type: "text",
    label: "Date Of Birth",
    name: "dob",
    placeholder: "Enter your Date Of Birth",
    required: true,
    // MM-DD-YYYY | YYYY-DD-MM | DD-MMM-YYYY
    format: "YYYY/MM/DD",
    minDate: "1980-01-01",
    maxDate: new Date(),
  },
  {
    interface: "file",
    label: "Profile Picture",
    name: "avatar",
    required: true,
    maxFiles: 2,
    themeColor: "green",
    accept: {
      "image/jpeg": [".jpeg", ".jpg"],
      "image/png": [".png"],
    },
  },
  {
    interface: "checkbox",
    name: "terms",
    label: "I agree to the terms and conditions",
    required: true,
  },
  // {
  //   interface: "radio",
  //   name: "gender_radio",
  //   label: "Gender",
  //   required: true,
  //   options: [
  //     { label: "Male", value: "male" },
  //     { label: "Female", value: "female" },
  //     { label: "Other", value: "other" },
  //   ],
  // },
];
